---

- name: Create users with their authorized key
  include_tasks: authorized_users.yml
  loop: "{{lookup('dict', users, wantlist=True)}}"

- name: Edit 'AllowUsers' in sshd_config
  become: true
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^AllowUsers"
    line: "AllowUsers {{ ansible_service_user }} {{ users.keys()|list|join }}"
    backup: 1
    validate: '/usr/sbin/sshd -T -f %s'
    state: present
  notify:
    - reload sshd
