matrix_domain: "{{ base_url }}"

matrix_awx_enabled: false

matrix_vars_yml_snapshotting_src: "{{ inventory_dir }}/host_vars/matrix.yml"

matrix_ssl_lets_encrypt_support_email: "{{ webmaster_email }}"

matrix_coturn_turn_static_auth_secret: "{{ vault_matrix_coturn_turn_static_auth_secret }}"

matrix_synapse_macaroon_secret_key: "{{ vault_matrix_synapse_macaroon_secret_key }}"

matrix_postgres_connection_password: "{{ vault_matrix_postgres_connection_password }}"

matrix_synapse_enable_registration: false

matrix_nginx_proxy_enabled: false

matrix_nginx_proxy_proxy_matrix_client_api_forwarded_location_synapse_oidc_api_enabled: true

matrix_nginx_proxy_proxy_matrix_nginx_status_enabled: true

#todo realm IMIS
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
    - idp_id: keycloak
      idp_name: "Keycloak"
      issuer: "https://auth.{{ base_url }}.com/auth/realms/IMIS"
      client_id: "synapse"
      client_secret: "{{ vault_keycloak_synapse_client_secret }}"
      scopes: ["openid", "profile"]
      user_mapping_provider:
        config:
          localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
          display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
matrix_jitsi_enabled: true

matrix_jitsi_jicofo_auth_password: "{{ vault_matrix_jitsi_jicofo_auth_password }}"
matrix_jitsi_jvb_auth_password: "{{ vault_matrix_jitsi_jvb_auth_password }}"
matrix_jitsi_jibri_recorder_password: "{{ vault_matrix_jitsi_jibri_recorder_password }}"
matrix_jitsi_jibri_xmpp_password: "{{ vault_matrix_jitsi_jibri_xmpp_password }}"
