hostname_nextcloud: "{{ host_specific_nextcloud_hostname }}"

nextcloud_user_username: nextcloud
nextcloud_user_uid: 3991
nextcloud_user_gid: 3991

# uid/gid that the Nextcloud HTTP server runs with
nextcloud_http_user_uid: 33
nextcloud_http_user_gid: 33

# Specifies the path to use for the `HOME` environment variable for systemd unit files.
# Docker 20.10 complains with `WARNING: Error loading config file: .dockercfg: $HOME is not defined`
# if `$HOME` is not defined, so we define something to make it happy.
nextcloud_systemd_unit_home_path: /root

# The Docker network that all services would be put into
nextcloud_docker_network: "nextcloud"

# Controls whether Docker is automatically installed.
# If you change this to false you must install and update Docker manually. You also need to install the docker (https://pypi.org/project/docker/) Python package.
nextcloud_docker_installation_enabled: true

# Controls the Docker package that is installed.
# Possible values are "docker-ce" (default) and "docker.io" (Debian).
nextcloud_docker_package_name: docker-ce

nextcloud_ntpd_package: "{{ 'systemd-timesyncd' if ansible_distribution == 'CentOS' and ansible_distribution_major_version > '7' else 'ntp' }}"
nextcloud_ntpd_service: "{{ 'systemd-timesyncd' if ansible_distribution == 'CentOS' and ansible_distribution_major_version > '7' else ('ntpd' if ansible_os_family == 'RedHat' or ansible_distribution == 'Archlinux' else 'ntp') }}"

# The architecture that your server runs.
# Recognized values by us are 'amd64'.
# Currently only 'amd64' is supported.
nextcloud_architecture: amd64

# The architecture for Debian packages.
# See: https://wiki.debian.org/SupportedArchitectures
# We just remap from our `nextcloud_architecture` values to what Debian and possibly other distros call things.
nextcloud_debian_arch: "{{ 'armhf' if nextcloud_architecture == 'arm32' else nextcloud_architecture }}"

nextcloud_base_data_path: "/nextcloud"
nextcloud_environment_variables_data_path: "{{ nextcloud_base_data_path }}/environment-variables"
nextcloud_external_storage_path: "{{ nextcloud_base_data_path }}/external-storage"
nextcloud_scratchpad_dir: "{{ nextcloud_base_data_path }}/scratchpad"

nextcloud_nextcloud_data_path: "{{ nextcloud_base_data_path }}/nextcloud-data"
nextcloud_nextcloud_docker_image: "docker.io/nextcloud:22.1.0-apache"

# Controls whether the nextcloud-apache container's memory usage
# is limited and to what extent.
#
# When set, these options are passed to `docker run`
# as `--memory=..` and `--memory-swap=..` respectively.
#
# Expected value format is `[integer][unit]`. E.g. 100M, 1G
#
# If `nextcloud_nextcloud_apache_container_memory_swap_limit` is set,
# it represents the total memory that can be used (memory + swap),
# so it must always be at least as large as `nextcloud_nextcloud_apache_container_memory_limit`.
# To disable swapping, make it the same as `nextcloud_nextcloud_apache_container_memory_limit`.
nextcloud_nextcloud_apache_container_memory_limit: ""
nextcloud_nextcloud_apache_container_memory_swap_limit: ""

# Controls whether the nextcloud-apache container exposes its HTTP port (tcp/80 in the container).
#
# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:37150"), or empty string to not expose.
nextcloud_nextcloud_apache_container_http_host_bind_port: "127.0.0.1:{{ nextcloud_apache_http_port_on_host }}"

# If `nextcloud_nginx_proxy_enabled` is set to `false`,
# nextcloud-apache's port 80 will be exposed to the container host (127.0.0.1)
# on this port by default.
nextcloud_apache_http_port_on_host: 37150

nextcloud_postgres_connection_hostname: "nextcloud-postgres"
nextcloud_postgres_connection_username: "nextcloud"
nextcloud_postgres_connection_password: "nextcloud-password"
nextcloud_postgres_db_name: "nextcloud"

nextcloud_postgres_docker_image_v9: "docker.io/postgres:9.6.23-alpine"
nextcloud_postgres_docker_image_v10: "docker.io/postgres:10.18-alpine"
nextcloud_postgres_docker_image_v11: "docker.io/postgres:11.13-alpine"
nextcloud_postgres_docker_image_v12: "docker.io/postgres:12.8-alpine"
nextcloud_postgres_docker_image_v13: "docker.io/postgres:13.4-alpine"
nextcloud_postgres_docker_image_latest: "{{ nextcloud_postgres_docker_image_v13 }}"

nextcloud_postgres_data_path: "{{ nextcloud_base_data_path }}/postgres"

# A list of configuration parameters for Nextcloud.
# To define your own, we advise editing `nextcloud_config_additional_parameters`.
nextcloud_config_parameters: "{{ nextcloud_config_default_parameters + nextcloud_config_additional_parameters }}"

# Default configuration parameters to apply to Nextcloud.
# To add your own additional parameters, use `nextcloud_config_additional_parameters`.
# To get rid of these defaults, redefine `nextcloud_config_default_parameters` or `nextcloud_config_parameters`.
nextcloud_config_default_parameters:
  - key: overwriteprotocol
    value: "https"
    type: string

# Add your custom Nextcloud configuration parameters here.
#
# Example:
# nextcloud_config_additional_parameters:
#   - key: mail_smtphost
#     value: smtp.example.com
#     type: string
nextcloud_config_additional_parameters: []


nextcloud_onlyoffice_enabled: false
nextcloud_onlyoffice_document_server_docker_image: "docker.io/onlyoffice/documentserver:6.4.0.121"

nextcloud_collabora_enabled: true
nextcloud_collabora_code_docker_image: "docker.io/collabora/code:6.4.10.10"

# If `nextcloud_nginx_proxy_enabled` is set to `true`,
# nextcloud-onlyoffice-document-server's port 80 is exposed to the container host (127.0.0.1)
# on this port by default.
nextcloud_onlyoffice_document_server_http_port_on_host: 37180

nextcloud_collabora_code_http_port_on_host: 37181
