---
# install docker and docker compose (on debian)

- name: ensure docker and docker-compose are present
  command: bash -c 'docker --version > /dev/null 2>&1 && docker-compose --version > /dev/null 2>&1'
  register: docker_and_compose_present
  tags: start

- name: update apt packages
  become: yes
  apt:
    state: latest
    update_cache: yes
    force_apt_get: yes
  when: docker_and_compose_present.rc != 0
  tags: start

- name: install or update packages for apt add repository over HTTPS
  become: yes
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  loop:
    - git
    - apt-transport-https
    - ca-certificates
    - wget
    - software-properties-common
    - gnupg2
    - curl
  when: docker_and_compose_present.rc != 0
  tags: start

- name: add apt signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: docker_and_compose_present.rc != 0
  tags: start


- name: add docker official repository for debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
  when: docker_and_compose_present.rc != 0
  tags: start

- name: update apt packages
  become: yes
  apt:
    state: latest
    update_cache: yes
    force_apt_get: yes
  when: docker_and_compose_present.rc != 0
  tags: start

- name: ensure docker is installed
  apt:
    name: "docker-ce"
    state: latest
  when: docker_and_compose_present.rc != 0
  tags: start

- name: make sure pip is installed
  apt:
    name: python3-pip
    update_cache: yes
  when: docker_and_compose_present.rc != 0
  tags: start

- name: update pip and install docker-compose
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - docker-compose
  when: docker_and_compose_present.rc != 0
  tags: start


# place compose file, start containers

- name: make sure working directory exists
  file:
    path: "/etc/keycloak"
    state: directory
    mode: 0777
  tags: start

- name: ensure docker-compose file is present
  template:
    src: "docker-compose.yml.j2"
    dest: "/opt/keycloak/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags: start

- name: ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true
  tags: start

- name: stop containers with docker_compose
  docker_compose:
    project_src: "/opt/keycloak"
    state: absent
  register: start_containers
  tags: stop

- name: ensure docker_compose containers are running
  docker_compose:
    project_src: "/opt/keycloak"
    state: present
  register: start_containers
  tags: start

- name: wait a few seconds, so that containers can start (or fail)
  wait_for:
    timeout: 15
  become: false
  delegate_to: 127.0.0.1
  when: start_containers.changed
  tags: start

# setup realm and client in keycloak 

- name: start admin session via keycloak cli
  command: docker exec -t keycloak /opt/jboss/keycloak/bin/kcadm.sh config credentials --server https://{{ keycloak.keycloak_url|quote }}/auth --realm master --user {{ keycloak.admin_user|quote }} --password {{ keycloak.admin_password|quote }}
  tags: start

- name: check if realm {{ keycloak.realm_name|quote }} exists
  command: bash -c 'docker exec -t keycloak /opt/jboss/keycloak/bin/kcadm.sh get realms --fields realm | grep -q {{ keycloak.realm_name|quote }}'
  register: realm_present
  tags: start

- name: create realm
  command: docker exec -t keycloak /opt/jboss/keycloak/bin/kcadm.sh create realms -s realm={{ keycloak.realm_name|quote }} -s enabled=true 
  when: realm_present.rc != 0 
  tags: start

- name: check if client synapse exists
  command: bash -c 'docker exec -t keycloak /opt/jboss/keycloak/bin/kcadm.sh get clients -r {{ keycloak.realm_name|quote }} --fields clientId | grep -q synapse'
  register: client_present
  tags: start

- name: create synapse client
  command: docker exec -t keycloak /opt/jboss/keycloak/bin/kcadm.sh create clients -r {{ keycloak.realm_name|quote }} -s clientId=synapse -s enabled=true -s 'redirectUris=["https://matrix.{{ keycloak.base_url|quote }}/_synapse/client/oidc/callback"]' -s bearerOnly=false -s publicClient=false -s standardFlowEnabled=true -s directAccessGrantsEnabled=true -s secret={{ keycloak.client_secret|quote }}
  when: client_present.rc != 0
  tags: start
