---

- name: Give trusted users ssh access to user {{ ansible_service_user }}
  become: true
  authorized_key:
    user: "{{ ansible_service_user }}"
    key: "{{ ansible_authorized_keys|map('extract', users)|map(attribute='ssh_key')|join('\n') }}"
    exclusive: yes

- name: Edit sshd config file
  become: true
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    backup: 1
    validate: '/usr/sbin/sshd -T -f %s'
    state: present
  loop: "{{ lookup('dict', sshd) }}"
  notify:
    - reload sshd

- name: Switch to '{{ ansible_service_user }}' to end root usage
  connection: local
  set_fact:
    ansible_user: "{{ ansible_service_user }}"

- name: Ensure that the reload handler will run
  meta: flush_handlers