---

- name: Install 'iptables'
  become: true
  apt:
    name: iptables

- name: Flush all firewall rules
  become: true
  iptables:
    flush: true

- name: ACCEPT ESTABLISHED on INPUT
  become: true
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED
    jump: ACCEPT

# Debian 11 needs this for SSH access
- name: ACCEPT all loopback traffic
  become: true
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: ACCEPT DNS
  become: true
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "53"
    jump: ACCEPT

- name: ALLOW SSH traffic
  become: true
  iptables:
    chain: INPUT
    destination_port: '22'
    protocol: tcp
    jump: ACCEPT

- name: ALLOW HTTP traffic
  become: true
  iptables:
    chain: INPUT
    destination_port: '80'
    protocol: tcp
    jump: ACCEPT

- name: ALLOW HTTPS traffic
  become: true
  iptables:
    chain: INPUT
    destination_port: '443'
    protocol: tcp
    jump: ACCEPT

- name: DROP INPUT
  become: true
  iptables:
    chain: INPUT
    jump: DROP


# NAT
- name: Forward all new HTTPS traffic to nginx container
  become: true
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    in_interface: "{{ interface.name }}"
    destination: "{{ interface.ip }}"
    destination_port: '443'
    jump: DNAT
    to_destination: '10.10.10.2:443'
    ctstate: NEW

 #todo use inventory
- name: Forward all new HTTP traffic to nginx container
  become: true
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    in_interface: "{{ interface.name }}"
    destination: "{{ interface.ip }}"
    destination_port: '80'
    jump: DNAT
    to_destination: '10.10.10.2:80'
    ctstate: NEW


- name: NAT the container subnet
  become: true
  iptables:
    table: nat
    chain: POSTROUTING
    source: '10.10.10.0/24'
    jump: SNAT
    to_source: "{{ interface.ip }}"

- name: Install 'iptables-persistent'
  become: true
  apt:
    name: iptables-persistent
