---

#########################################################################
# This follows the official documentation provided at:                  #
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye #
#########################################################################

- name: Fail if not running on Debian 11 (Bullseye)
  fail:
    msg: "Only Debian 11 (Bullseye) is supported"
  when: ansible_distribution != "Debian" or ansible_distribution_version|int != 11

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

# https://gist.github.com/rothgar/8793800
- name: Template /etc/hosts file
  become: true
  template:
    src: etc/hosts.j2
    dest: /etc/hosts

- name: Set a hostname to {{ inventory_hostname }}
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Resolve own hostname
  shell: hostname --ip-address
  register: resolved_ip

- name: Fail if hostname does not resolve correctly
  fail:
    msg: "Own hostname could not be resolved correctly"
  when: resolved_ip == proxmox.public_ip

- name: Ensure that gpg is available for the next operations
  become: true
  apt:
    name: gpg

- name: Add the Proxmox VE repository key
  become: true
  get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    checksum: sha512:7fb03ec8a1675723d2853b84aa4fdb49a46a3bb72b9951361488bfd19b29aab0a789a4f8c7406e71a69aabbc727c936d3549731c4659ffa1a08f44db8fdcebfa

- name: Add the Proxmox VE repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
    filename: pve-install-repo

- name: Update the complete system
  become: true
  apt:
    upgrade: full
    update_cache: yes

# https://serverfault.com/questions/1068990/what-is-the-most-reliable-way-to-install-ifupdown2-via-ansible
- name: Install ifupdown2
  become: true
  shell: apt-get install -y ifupdown2 && systemctl restart networking
  async: 180
  poll: 5

# Note we configure postfix later with role `postfix`
- name: Install proxmox-ve, postfix and open-iscsi packages
  become: true
  apt:
    pkg:
      - proxmox-ve
      - postfix
      - open-iscsi

- name: Disable enterprise package
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise'
    line: '# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise'


- name: Add Proxmox VE No-Subscription repository
  become: true
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present

- name: Reboot host and wait for it to restart
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30

- name: Remove the os-prober package as recommended
  become: true
  apt:
    name: os-prober
    state: absent

# todo add root user
# sudo pveum user add hans.wurst@pve -password password
# sudo pveum acl modify / -user hans.wurst@pve -role Administrator
# sudo pveam download local debian-11-standard_11.0-1_amd64.tar.gz
# todo setup network https://docs.ansible.com/ansible/latest/collections/community/general/interfaces_file_module.html
# https://localhost:8080/pve-docs/chapter-sysadmin.html#sysadmin_network_configuration
# Add the following to /etc/network/interfaces
#
#auto vmbr0
##private sub network
#iface vmbr0 inet static
#        address  10.10.10.1
#        netmask  255.255.255.0
#        bridge-ports none
#        bridge-stp off
#        bridge-fd 0
#
#        post-up   echo 1 > /proc/sys/net/ipv4/ip_forward
#
# then execute sudo ifreload -a