---

- name: Fail if not running on Debian 11 (Bullseye)
  fail:
    msg: "Only Debian 11 (Bullseye) is supported"
  when: ansible_distribution != "Debian" or ansible_distribution_version|int != 11

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

# todo hostname?

# see https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye
- name: Template /etc/hosts file
  become: true
  template:
    src: etc/hosts.j2
    dest: /etc/hosts

- name: Resolve own hostname
  shell: hostname --ip-address
  register: resolved_ip

- name: Fail if hostname does not resolve correctly
  fail:
    msg: "Own hostname could not be resolved correctly"
  when: resolved_ip == {{ ansible_facts.eth0.ipv4.address }}

- name: Add the Proxmox VE repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
    filename: pve-install-repo

- name: Add the Proxmox VE repository key
  become: true
  ansible.builtin.apt_key:
    id: DD4BA3917E23BF59
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    keyring: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg

- name: Compute sha512 sum of /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
  stat:
    path: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    checksum_algorithm: sha512
    get_checksum: yes
  register: sha_proxmox_gpg_key

- name: Verify sha 512hash of /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
  fail:
    msg: "Verification of GPG key failed"
  when: sha_proxmox_gpg_key != '7fb03ec8a1675723d2853b84aa4fdb49a46a3bb72b9951361488bfd19b29aab0a789a4f8c7406e71a69aabbc727c936d3549731c4659ffa1a08f44db8fdcebfa'

- name: Update the complete system
  become: true
  apt:
    upgrade: full
    update_cache: yes

# Note we configure postfix later with role `postfix`
- name: Install install proxmox-ve, postfix and open-iscsi packages
  become: true
  apt:
    pkg:
      - proxmox-ve
      - postfix
      - open-iscsi

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30

- name: Remove the os-prober package as recommended
  become: true
  apt:
    name: os-prober
    state: absent
