---

# Pre-checks

- name: Fail if playbook called incorrectly
  fail:
    msg: "The `server_path_postgres_dump` variable needs to be provided to this playbook, via --extra-vars"
  when: "server_path_postgres_dump is not defined or server_path_postgres_dump.startswith('<')"

- name: Check if the provided Postgres dump file exists
  stat:
    path: "{{ server_path_postgres_dump }}"
  register: result_server_path_postgres_dump_stat

- name: Fail if provided Postgres dump file doesn't exists
  fail:
    msg: "File cannot be found on the server at {{ server_path_postgres_dump }}"
  when: "not result_server_path_postgres_dump_stat.stat.exists"


# Defaults

- name: Set postgres_start_wait_time, if not provided
  set_fact:
    postgres_start_wait_time: 15
  when: "postgres_start_wait_time|default('') == ''"

- name: Set postgres_import_wait_time, if not provided
  set_fact:
    postgres_import_wait_time: "{{ 7 * 86400 }}"
  when: "postgres_import_wait_time|default('') == ''"

# Actual import work

- name: Ensure nextcloud-postgres is started
  service:
    name: nextcloud-postgres
    state: started
    daemon_reload: yes

- name: Wait a bit, so that Postgres can start
  wait_for:
    timeout: "{{ postgres_start_wait_time }}"
  delegate_to: 127.0.0.1
  become: false

- import_tasks: tasks/util/detect_existing_postgres_version.yml

- name: Abort, if no existing Postgres version detected
  fail:
    msg: "Could not find existing Postgres installation"
  when: "not nextcloud_postgres_detected_existing|bool"

# Starting the database container had automatically created the default
# role (`nextcloud_postgres_connection_username`) and database (`nextcloud_postgres_db_name`).
# The dump most likely contains those same entries and would try to re-create them, leading to errors.
# We need to skip over those lines.
- name: Generate Postgres database import command
  set_fact:
    nextcloud_postgres_import_command: >-
      /usr/bin/env docker run --rm --name nextcloud-postgres-import
      --log-driver=none
      --cap-drop=ALL
      --network={{ nextcloud_docker_network }}
      --env-file={{ nextcloud_environment_variables_data_path }}/env-postgres-pgsql-docker
      --mount type=bind,src={{ server_path_postgres_dump }},dst=/{{ server_path_postgres_dump|basename }},ro
      --entrypoint=/bin/sh
      {{ nextcloud_postgres_docker_image_latest }}
      -c "cat /{{ server_path_postgres_dump|basename }} |
      {{ 'gunzip |' if server_path_postgres_dump.endswith('.gz') else '' }}
      grep -vE '^CREATE ROLE {{ nextcloud_postgres_connection_username }}' |
      grep -vE '^CREATE DATABASE {{ nextcloud_postgres_db_name }}' |
      psql -v ON_ERROR_STOP=1 -h nextcloud-postgres"

# This is a hack.
# See: https://ansibledaily.com/print-to-standard-output-without-escaping/
#
# We want to run `debug: msg=".."`, but that dumps it as JSON and escapes double quotes within it,
# which ruins the command (`nextcloud_postgres_import_command`)
- name: Note about Postgres importing alternative
  set_fact:
    dummy: true
  with_items:
    - >-
        Importing Postgres database using the following command: `{{ nextcloud_postgres_import_command }}`.
        If this crashes, you can stop Postgres (`systemctl stop nextcloud-postgres`),
        delete its existing data (`rm -rf {{ nextcloud_postgres_data_path }}/*`), start it again (`systemctl start nextcloud-postgres`)
        and manually run the above import command directly on the server.

- name: Perform Postgres database import
  command: "{{ nextcloud_postgres_import_command }}"
  async: "{{ postgres_import_wait_time }}"
  poll: 10
