---

- name: Ensure the system is up to date
  apt:
    update_cache: yes
    upgrade: yes

- name: Ensure APT usage dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Ensure Docker's APT key is trusted
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Ensure Docker repository is enabled
  apt_repository:
    repo: "deb [arch={{ nextcloud_debian_arch }}] https://download.docker.com/linux/debian bullseye stable"
    state: present
    update_cache: yes

- name: Ensure APT packages are installed
  apt:
    name:
      - "{{ nextcloud_ntpd_package }}"
      - fuse
    state: latest
    update_cache: yes

- name: Ensure Docker is installed
  apt:
    name:
      - "docker-ce"
      - "python3-docker"
    state: latest

- name: Ensure Docker is started and autoruns
  service:
    name: docker
    state: started
    enabled: yes

- name: "Ensure {{ nextcloud_ntpd_service }} is started and autoruns"
  service:
    name: "{{ nextcloud_ntpd_service }}"
    state: started
    enabled: yes
