---

- name: Ensure Nextcloud group is created
  group:
    name: "{{ nextcloud_user_username }}"
    gid: "{{ nextcloud_user_gid }}"
    state: present

- name: Ensure Nextcloud user is created
  user:
    name: "{{ nextcloud_user_username }}"
    uid: "{{ nextcloud_user_gid }}"
    group: "{{ nextcloud_user_username }}"
    state: present

- name: Ensure environment variables data path exists
  file:
    path: "{{ nextcloud_environment_variables_data_path }}"
    state: directory
    mode: 0700

- name: Ensure Nextcloud base path exists
  file:
    path: "{{ nextcloud_base_data_path }}"
    state: directory
    mode: 0750
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"

- name: Ensure Nextcloud network is created in Docker
  docker_network:
    name: "{{ nextcloud_docker_network }}"
    driver: bridge
