---

- hosts: dedicated
  gather_facts: false
  roles:
    - role: ssh-initial
    - role: iptables
      tags:
        - never

- hosts: dedicated
  roles:
    - role: proxmox-initial
      tags:
        - never
