---

- hosts: dedicated
  gather_facts: false
  roles:
    - role: user-initial
      tags:
        - initial

- hosts: dedicated
  roles:
    - role: ssh-initial
      tags:
        - initial
    - role: iptables
      tags:
        - initial
    - role: proxmox-initial
      tags:
        - initial
