---

- hosts: dedicated
  gather_facts: false
  roles:
    - role: ssh-initial
      tags:
        - never

- hosts: dedicated
  roles:
    - role: proxmox-initial
      tags:
        - never
    - role: host-users
      tags:
        - users
        - never
