---

- name: Ensure the system is up to date
  apt:
    update_cache: yes
    upgrade: yes

- name: Ensure nginx is installed
  apt:
    name:
      - nginx
    state: present
    update_cache: yes

- name: Ensure nginx.conf is present
  template:
    src: "{{ role_path }}/templates/nginx/base/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644

- name: Ensure sites-enabled/default is present
  template:
    src: "{{ role_path }}/templates/nginx/base/default.j2"
    dest: "/etc/nginx/sites-enabled/default"
    mode: 0644

- name: Ensure periodic restarting of nginx is configured
  template:
    src: "{{ role_path }}/templates/cron.d/nginx-periodic-restarter.j2"
    dest: "/etc/cron.d/nginx-periodic-restarter"
    mode: 0600

- name: Ensure service configs are enabled
  template:
    src: "{{ role_path }}/templates/nginx/services/{{ item }}.j2"
    dest: "/etc/nginx/sites-available/{{ item }}"
    mode: 0644
  when: "{{ item }}.enabled"
  loop:
    - nextcloud

- name: Ensure service nginx is enabled and ensure it is not masked
  systemd:
    name: nginx
    enabled: yes
    masked: no

- name: Make sure nginx is running, restart if it was running
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
